### PR TITLE
Implementing 2 Factor Authentication

### PR DESCRIPTION
**Pull request by janet-barbie**
### PR Description
This pull request implements 2 factor authentication
### Description of tasks that were expected to be completed
A user should be able to enable and disable two factor authentication.
### Functionality
Login and  enable two factor authentication you will be sent a notification email.  try to Login an email with an otp code will be sent and two way verification  token in your response  .then loginWithTwoFactorAuthentication  provide a two way verification token and an otp code  
### How has this been tested?
 Tested using graphql appolo server
### PR Checklist:
- [X] Enable Two Factor Authentication.
- [X] Disable Two Factor Authentication.
- [X] Login With Two Factor Authentication.
### Track PR
Trello Link (#DP-?)
Screenshot 2024-11-04 at 16 04 50
Screenshot 2024-11-04 at 16 06 51
Screenshot 2024-11-04 at 17 02 22
Screenshot 2024-11-04 at 16 07 29

(Images)

### CODE REVIEW

**Review by JacquelineTuyisenge — APPROVED** [review]

**Review by Bananayosostene — APPROVED** [review]

**Review by RWEMAREMY — APPROVED** [review]
great work

**Review by RWEMAREMY — APPROVED** [review]
Good job

**Comment by Salim-54** [comment]
Resolve conflicts

**Review by RWEMAREMY — APPROVED** [review]
Good job

**Pull request merged**
