### PR TITLE
Fix: Continous integration setup

### PR DESCRIPTION
**Pull request by feyton**
### PR Description
This pull request ensure that the run on github action use the image provided by github
This will ensure consistent runs and fast runs without the dependency on third parties

### Tasks that are completed
- [ ] Ensure that the runs are handled using mongo image
- [ ] Ensure the name are consistent

### Background context
The prior setup relied on using a test db shared across multiple runs. This lead to data collision and as the application grows, it would not be sustainable
Since github allow user to setup custom services (`Docker images`), this pull request ensures that we are using github resources which gurantee fast run

### CODE REVIEW

**Review by Procech20 — COMMENTED** [review]
You can try to use the secrets and hide the database and environment in use

**Comment by feyton** [comment]
> You can try to use the secrets and hide the database and environment in use

Where exactly

**Review by chanceDira — APPROVED** [review]
Good job @feyton

**Review by rukundo-kevin — APPROVED** [review]

**Review by jeandamascyifuzo — APPROVED** [review]
well done @feyton

**Pull request merged**
