### PR TITLE
chore: setup database

### LINKED ISSUE #8: Add SSL to droplet
# Description
Add an SSL certificate to our droplet so requests are secured.

### PR DESCRIPTION
**Pull request by Procech20**
### PR Description
This PR successfully setup database and configures the ORM

### Description of tasks that were expected to be completed
1.  The application must be able to connect to the database
2. The server is configured
3. The SSL certificate has been added and a redirect has been configured
4. The ORM has been setup and database connection is established 

### Functionality 
This has successfully setup the server and the database

### How has this been tested?
This PR adds placeholder queries and resolvers. To test the functionality, you can access the hosted version from here

**[Hosted version](https://161.35.150.208/)**

All queries and resolvers should be working correctly

- [x] I am able to create new user
- [x] I am able to get a list of all users
- [x] I can inspect the graph for the expected data

### Screenshots (If appropriate)
image

### CODE REVIEW

**Review by chanceDira — COMMENTED** [review]
Can you provide this file .env.example

**Review by feyton — APPROVED** [review]
### Approved

**Review by ceelogre — DISMISSED** [review]
image
Remove the packages that are no longer needed.

**Review by PatrickTUy — APPROVED** [review]
This looks fine

**Comment by ceelogre** [comment]
Are we now able to access the backend app via droplet IP?

**Review by ceelogre — COMMENTED** [review]
Are we now able to access the backend app and db via droplet IP?

**Review by feyton — CHANGES_REQUESTED** [review]
### Issue investigation

Am facing this issue when I try to run the project
image

I tried
- Renstallation of node_modules (`npm i` and `npm ci`) does not solve the issue
- Deleted the node_modules does not solve the issue

Please investigate and let me know if this is happening on my end only.

**Review by feyton — APPROVED** [review]

**Comment by ceelogre** [comment]
How should we access this?

**Review by samyshyaka — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
