### PR TITLE
fix program and cohort dp-118

### PR DESCRIPTION
**Pull request by Tsa2341**
### PR Description

This PR fixes the program and cohorts' minor bugs in the implementation and implement update and delete of programs and cohorts.

### Description of tasks that were expected to be completed

- [x] fix dropdowns for users selection
- [x] add update and delete of programs and cohorts
- [x] format dates in tables
- [x] add validation for dates
- [x] fix space between the two words on the modals' title

### functionality

mutation UpdateProgram($updateProgramId: ID!, $name: String, $description: String, $orgToken: String) {
  updateProgram(id: $updateProgramId, name: $name, description: $description, orgToken: $orgToken) {
    id
  }
}
mutation DeleteProgram($deleteProgramId: ID!) {
  deleteProgram(id: $deleteProgramId) {
    id
    name
  }
}
mutation UpdateCohort($updateCohortId: ID!, $phase: String) {
  updateCohort(id: $updateCohortId, phase: $phase) {
    id
    name
    phase
    startDate
    endDate
  }
}
mutation DeleteCohort($deleteCohortId: ID!) {
  deleteCohort(id: $deleteCohortId) {
    id
    name
  }
}

### How has this been tested?

git clone https://github.com/atlp-rwanda/atlp-pulse-bn.git
cd atlp-pulse-bn
git checkout fix-programs-and-cohorts-dp-118
npm i
npm run seed
npm run dev

Also, open and run the command on this [Front-end Integration](https://github.com/atlp-rwanda/atlp-pulse-fn/pull/121) PR, and follow the instruction on it to test the app.

### Track PR

[trello link to card](https://trello.com/c/DHcwCyje)

### CODE REVIEW

**Review by Himbaza123h — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

**Comment by Procech20** [comment]
@Tsa2341 what are the minor bugs that the PR fixes and what are the steps to take in order to test that it works and what are the expected output?

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by Procech20 — APPROVED** [review]

**Review by Procech20 — CHANGES_REQUESTED** [review]
The changes works fine but why does your branch still have the [ci-pipeline workflow](https://github.com/atlp-rwanda/atlp-pulse-bn/tree/fix-programs-and-cohorts-dp-118/.github/workflows/ci-pipeline.yml) which was removed? Have you rebased properly?!

**Review by Procech20 — CHANGES_REQUESTED** [review]
@Tsa2341 Your branch has 3 workflows including the [CI-pipeline](urlhttps://github.com/atlp-rwanda/atlp-pulse-bn/tree/fix-programs-and-cohorts-dp-118/.github/workflows/ci-pipeline.yml) which has been removed!

prog cohorts PR - branch

Check the workflows file on develop

prog cohorts PR - dev

**Comment by Tsa2341** [comment]
@Procech20, I was actually deleting it but because it was already on GitHub it wasn't being reflected on the remote repo. But now it is done, you can re-review.

**Review by Procech20 — APPROVED** [review]

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-bn-review-app-33.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Pull request closed without merging**
