### PR TITLE
#DP-111 fix: Update profile picture

### PR DESCRIPTION
**Pull request by samyshyaka**
#### What does this PR do?
Enables a user to update their profile picture

#### Description of the tasks to be completed
- [x] Users should be able to update their avatar
 
#### How should this be manually tested?
- Run the commands below in your terminal
```js
git checkout fx-picture-upload
git fetch
npm install
npm run dev
open http://localhost:4000/
```
- Use the frontend to change your profile picture and cover image

#### Pre-requisites:

- Clone both the frontend and backend versions of the project

#### Relevant trello story:
[#DP-111](https://trello.com/c/AYiItUdt/111-profile-picture-update)

### CODE REVIEW

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
Please provide the following keys to test locally: 
 CLOUD_NAME=<cloud-name>
API_KEY=<cloudinary-api-key>
API_SECRET=<cloudinary-api-secret>

**Comment by samyshyaka** [comment]
> Please provide the following keys to test locally: CLOUD_NAME= API_KEY= API_SECRET=

We are not using them anymore

**Review by PatrickTUy — DISMISSED** [review]
nice work @samyshyaka, can the user also get to update the  cover Image, it's not being updated

**Review by feyton — APPROVED** [review]
This is great work @samyshyaka

**Review by Dev-nkundineza — APPROVED** [review]
Good work @samyshyaka

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by chanceDira — APPROVED** [review]

**Review by ceelogre — COMMENTED** [review]
Where is the link to the review app?

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-bn-review-app-27.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Procech20 — APPROVED** [review]
Please resolve the conflicts

**Review by Procech20 — COMMENTED** [review]
Please resolve the conflicts!

**Pull request closed without merging**
